name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: gradle/actions/wrapper-validation@main

      - name: Set up JDK
        uses: graalvm/setup-graalvm@main
        with:
          java-version: 21
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew build

      - name: Artifact Curios API
        uses: actions/upload-artifact@main
        with:
          name: Curios API
          path: build/libs/Curios API-*.jar
